timeout: 10m
dependency-tree: true
list-all-pkgs: true
exit-code: 1
severity:
  - HIGH
  - CRITICAL
scan:
  scanners:
    - vuln
    - secret
    - misconfig
    - license
vulnerability:
  type:
    - os
    - library
  ignore-unfixed: true
