[helpers]

[default]
depends = []

[default.files]
Justfile = ""
LICENSE = ""
"README.md" = ""
docs = ""
"lefthook.yml" = ""
"oh-my-posh.json" = ""

[default.variables]

[settings]
default_target_type = "automatic"
