# labels auto assigned to PR, keep in sync with labels.yml
# Type
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["README.md", "*.md", "docs/**"]
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/uv.lock", "package-lock.json"]
      - head-branch: ["^dependabot"]
configurations:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              [
                ".github/other-configurations/*",
                ".github/super-linter-configurations/*",
              ]
# Language
markdown:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              [
                "docs/*.md",
                "*.md",
                "LICENSE",
                ".github/pull_request_template.md",
              ]
python:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["*.py", "**/*.py"]
typescript:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              ["*.ts", "*.tsx", "**/*.ts", "**/*.tsx", "**/tsconfig.json"]
shell:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/*.sh"]
just:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["Justfile", "**/*.just"]
# Components
git_hooks:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["lefthook.yml"]
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/workflows/*", ".github/actions/*"]
