# Default GitHub labels
- color: d73a4a
  name: bug
  description: Something isn't working
- color: fef2c0
  name: configurations
  description: Pull requests that update configuration files
- color: 0075ca
  name: documentation
  description: Improvements or additions to documentation
- color: 0366d6
  name: dependencies
  description: Pull requests that update a dependency file
- color: cfd3d7
  name: duplicate
  description: This issue or pull request already exists
- color: a2eeef
  name: enhancement
  description: Functionality that enhances existing features
- color: 7057ff
  name: good first issue
  description: Good for newcomers
- color: 008672
  name: help wanted
  description: We are looking for community help
- color: e4e669
  name: invalid
  description: This doesn't seem right
- color: d876e3
  name: question
  description: Further information is requested
- color: d876e3
  name: wontfix
  description: The issue is expected and will not be fixed
# Languages
- color: 000000
  name: github_actions
  description: Pull requests that update GitHub Actions code
- color: 00ff44
  name: shell
  description: Pull requests that update Shell code
- color: 1900ff
  name: markdown
  description: Pull requests that update Markdown documentation
- color: 66A615
  name: just
  description: Pull requests that update Just code
- color: 2b67c6
  name: python
  description: Pull requests that update Python code
- color: 00ff1e
  name: typescript
  description: Pull requests that update TypeScript code
# Components
- color: ff0073
  name: git_hooks
  description: Pull requests that update git hooks
# Sizes
- color: 00ff22
  name: size/XS
  description: Extra Small Pull Request
- color: 03a319
  name: size/S
  description: Small Pull Request
- color: f2bb05
  name: size/M
  description: Medium Pull Request
- color: fc7e08
  name: size/L
  description: Large Pull Request
- color: ad2e03
  name: size/XL
  description: Extra Large Pull Request
- color: 751f01
  name: size/XXL
  description: Extra Extra Large Pull Request
